### ISSUE TITLE
"label likelihoods"

### ISSUE THREAD

**Issue by cscherrer** [GaloisInc/ppaml-cp6#7]
It's a bit nitpicky, but technically "likelihood" is the wrong word here. 

Can you change this to "label posterior probabilities"? Or, if they're not necessarily probabilities, maybe "label score", with a sentence or two about the actual meaning of the number?

Thanks!

**Comment by collinsr** [comment]
Sure... if I'm reading the [paper](http://www.image-net.org/projects/hedging/) via the [webpage](http://caffe.berkeleyvision.org/gathered/examples/web_demo.html) correctly, the score associated with label X is the *information gain* from selecting X over one of X's more-specific child nodes in the ImageNet hierarchy. I'll change it in the documentation.

**Comment by cscherrer** [comment]
Great. I'll leave it to you to close this issue after the update. Thanks!

**Comment by collinsr** [comment]
Chad--

I've updated the problem statement in the dev/refactor branch of the git repository. This includes changes to the image indicator table (added a field) and descriptions of the CSIFT and Caffe tables. This corresponds to what I just updated in the sandboxes on PPAML and what Eran is running now to verify. If this looks good, I'll merge to master.

Thanks
-Roddy

**Comment by collinsr** [comment]
Merged dev/refactor branch in; documentation is now synchronized with the sandboxes on MIDAS.
