### ISSUE TITLE
Index out of bounds running `run.sh`

### ISSUE THREAD

**Issue by mhuesch** [GaloisInc/ppaml-cp6#8]
Hi,

I have been poking around trying to get `run.sh` working and encountered the following error:

```
Attempted to access model.pairs(:,1); index out of bounds because size(model.pairs)=[0,0].

Error in find_node2pair_arrays_ver2 (line 12)
for(c=1:length(model.pairs(:,1)))

Error in database_model (line 58)
[model.N1, model.N2] = find_node2pair_arrays_ver2(model);%!!! Not sure what this is used for

Error in extract_marbl_model_data_files (line 56)
model = database_model(1,length(data_locs),nvals, cliq_mat);%This is the format for the JGMT crf model, but this toolbox only handles pairwise cliques

Error in wrapper_crf_database_labeling_v2 (line 206)
                extract_marbl_model_data_files(cliq_flags, ex_train_locs, TopN, img_info_list, ...

Error in run (line 63)
evalin('caller', [script ';']);
 
12  for(c=1:length(model.pairs(:,1)))
```

I followed the README instructions (I think), downloading the archive `CP5-ImageLabeling > evaluation > sandboxes > round-1-public-sandbox.tgz` from MIDAS. I downloaded marbl and swapped out the learn_CRF.cpp file. I modified `marbl_path` in crf_config_file.m to point to the marbl_master directory which contains the build artifacts. Is there something I'm missing?

Thanks!

**Comment by eswears** [comment]
This is most likely a path or configuration issue. You need to cd to the “round-1-public” folder and run.sh from there.  If that is what you did, then we could go back and forth trying to figure it out, but it would be faster and easier if I can get a copy of your workspace.

 

To do this, run the main file, wrapper_crf_database_labeling_v2.m, until it crashes and then go up the debugging stack to the main file.  Type “save crf_state.mat” in the command window and send me the crf_state.mat file: eran.swears@kitware.com.  

 

This may be a very large file, so if you have a dropbox account, that may be easier.

 

-Eran

**Comment by collinsr** [comment]
Another option for transferring the file is to go to

http://www.kitware.com/upload

...and then send us an email saying you've sent the file. (I don't think Kitware's upload page notifies us automatically.)

-Roddy

**Comment by mhuesch** [comment]
I've just emailed Eran the file, which was only 1.6MB

**Comment by eswears** [comment]
Michael,

 

It looks like the “f_load_edges” flag in the crf_config_file.m (line 8) is set to “1”. This should be set to “0” the first time that you run it and then you can change it to “1” if you want to run it again and not have to wait for the edge file to be parsed.

 

I created a branch where the change is already made: config_commit.  

 

Let me know if you have any other problems,

Eran

**Comment by mhuesch** [comment]
Ah, ok. I didn't realize I had to change the value in the config file. I think it would be helpful if the README explicitly said to make that change in the instructions (and also if it mentioned the config file name - not too hard to figure out but would be simpler).

I have it running now. Thanks for the prompt responses!

**Comment by eswears** [comment]
Thanks for the feedback. I changed the code to have a default of “0” instead of “1”, so now it’s consistent with the readme. I’ll add the name of the config file to the readme. 

 

-Eran

**Comment by mhuesch** [comment]
Cool, thanks for incorporating that. I was trying to run the "round-1-demo" data since the "round-1-public" takes a while to complete, and I am seeing the same error I first posted in this issue:

```
Attempted to access model.pairs(:,1); index out of bounds because size(model.pairs)=[0,0].

Error in find_node2pair_arrays_ver2 (line 12)
for(c=1:length(model.pairs(:,1)))

Error in database_model (line 58)
[model.N1, model.N2] = find_node2pair_arrays_ver2(model);%!!! Not sure what this is used for

Error in extract_marbl_model_data_files (line 56)
model = database_model(1,length(data_locs),nvals, cliq_mat);%This is the format for the JGMT crf model, but this toolbox only handles pairwise cliques

Error in wrapper_crf_database_labeling_v2 (line 206)
                extract_marbl_model_data_files(cliq_flags, ex_train_locs, TopN, img_info_list, ...

Error in run (line 63)
evalin('caller', [script ';']);
 
12  for(c=1:length(model.pairs(:,1)))
```

I will email my debug file to Eran.

**Comment by collinsr** [comment]
Keep in mind that the demo sandboxes aren't semantically coherent; they're
only there to exercise the parsers. You shouldn't expect to get any actual
results on them.  I'd try the toy sandbox instead, which is about the same
size as the demo sandbox and is coherent.

-Roddy

**Comment by mhuesch** [comment]
Thanks for the tip Roddy. When I try running in the toy sandbox, though, I see this:

```
Undefined function or variable "label_vector".

Error in extract_image_table_structure (line 84)
        cur_img_info_list.label_vector= label_vector';

Error in load_files_extract_structures (line 18)
img_info_list= extract_image_table_structure(img_table, f_read_all_img_data);

Error in wrapper_crf_database_labeling_v2 (line 118)
[img_info_list, group_edges, word_edges, same_info_edges, keep_Word_ind_LUT, keep_Group_ind_LUT, cliq_flags]= ...

Error in run (line 63)
evalin('caller', [script ';']);
 
84          cur_img_info_list.label_vector= label_vector';
```

It seems like there are code paths which do not define label_vector, causing it to be defined in following code.

**Comment by mhuesch** [comment]
My goal is to produce run_out output so I can test feeding that into the `cp6_eval.py` script to test the evaluator. I'm currently running the `round-1-public` sandbox but it takes a while to complete so I was hoping to run a smaller sandbox and get the output faster. Is there an easier way to accomplish this?

Thanks!

**Comment by collinsr** [comment]
Probably the quickest way is to copy the image_table.txt from run_in to
run_out and then run the cp6_eval.py script with the "--r p" option to
generate random scores shaped as the label priors. That will generate valid
score csv on stdout.  (If you run cp6_eval.py with '--h' it should print
its options.)

-Roddy

**Comment by mhuesch** [comment]
Cool, I have tried that and it works.

My long run in the "round-1-public" sandbox just errored out with this:
```
../marbl-master/learn_CRF: /home/peval/packages/MATLAB/R2014a/sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by ../marbl-master/learn_CRF)
../marbl-master/infer_CRF: /home/peval/packages/MATLAB/R2014a/sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by ../marbl-master/infer_CRF)
Index exceeds matrix dimensions.

Error in wrapper_crf_database_labeling_v2 (line 262)
            cell_node_marginals= cellfun(@str2num,marginal_file(1:test_model.nnodes),'uniformoutput',false);

Error in run (line 63)
evalin('caller', [script ';']);
 
262             cell_node_marginals= cellfun(@str2num,marginal_file(1:test_model.nnodes),'uniformoutput',false);
```

I've saved the debug output and can send it to Eran. I assume you guys are able to run to completion on your end by following the README instructions?

**Comment by collinsr** [comment]
That sounds like an LD_LIBRARY_PATH issue... If you run ldd on learn_crf or
infer_crf, does it report any missing libraries? Can you run those binaries
directly from the command line to get a usage message?

**Comment by eswears** [comment]
The parser was designed with some built in assumptions that were only valid for the MIR sandbox data.  I added some patches today to make it more general. I can push it to the config_commit branch tomorrow when I get to the right PC.

 

-Eran

**Comment by eswears** [comment]
The Troubleshooting section of the README.txt has the solution for this.  I ran into the same problem when I was originally getting things to run.

 

-Eran

**Comment by eswears** [comment]
I pushed some revisions to the crf_config branch to handle more datasets.  I also added words from titles, comments, and descriptions to the feature set.  It was previously just tags, but there aren’t enough words in the tags for smaller datasets.  I tested it on the round-1-demo data and it is currently running on the round-1-public data.  

 

-Eran

**Comment by mhuesch** [comment]
learn_CRF & infer_CRF seem to work

```
$ ../marbl-master/infer_CRF -h
Error! no model flag found! (-m)
terminate called after throwing an instance of 'MyException'
  what():  Error! no model flag found! (-m)
Aborted (core dumped)

$ ../marbl-master/infer_CRF 
Error! no model flag found! (-m)
terminate called after throwing an instance of 'MyException'
  what():  Error! no model flag found! (-m)
Aborted (core dumped)
```

I will try the crf_config branch. Thanks!

**Comment by mhuesch** [comment]
I am not seeing a `crf_config` branch. Is it pushed to the remote?

**Comment by eswears** [comment]
It’s on origin now…

 

-Eran

**Comment by mhuesch** [comment]
Closing this since I've gotten the `config_commit` branch to work. Thanks!
